image: maven:3.6.1
clone:
  depth: full
pipelines:
  branches:
    main:
    - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
    - step:
          script:
            - git push -f https://heroku:2d2e8e06-2ae1-4d90-91b7-e17f2bfe0998@git.heroku.com/dev-portalelysium.git $BITBUCKET_BRANCH